export const courses = [
  "Front-end Web Development",
  "Product Design",
  "Project Management",
  "Cloud Computing",
  "Cybersecurity",
  "Data Analytics",
  "Digital Marketing",
  "Video Editing",
  "Introduction to Web3 Technologies",
  "Professional Graphics Design",
  "Product Management",
  "Architectural Design & 3D Visualization",
  "Structural Engineering Design & Analysis",
  "MEP (Mechanical, Electrical & Plumbing) Design",
  "Digital Productivity & Collaboration",
  "YouTube Development & Optimization",
  "Social Media Optimization",
  "Professional Use of Excel",
  "Staff Training on use of digital workspace & tools",
];
